import { ColDef } from "ag-grid-community";
import { AgGridFilter } from "./aggrid";

export enum ExcelFieldName {
  FIO,
  EDUCATION_ORG,
  CITY,
  SEX,
  CLASS_NAME,
  CLASS,
  EXAMINATION_DATE,
  BIRTHDAY,
  AGE,
  EXPERIENCE,
  SPORT_KIND,
  HEALTH_GROUP,
  PHYSICAL_GROUP,
  DISEASES_YEAR_NUMBER,
  DISEASES_YEAR_DURATION,
  GROWTH,
  WEIGHT,
  OKG_REST,
  OKG_SIGH,
  OKG_EXHALATION,
  ZHEL,
  KD_RIGHT,
  KD_LEFT,
  KZHS_UNDER_UNDER_SHOULDER,
  KZHS_ON_BELLY,
  KZHS_ON_BICEPS,
  AD_SYSTOLIC,
  AD_DIASTOLIC,
  CHSS_LOAD,
  CHSS_REST,
  CHSS1,
  CHSS2,
  CHSS3,
  CHSS4,
  CHSS5,
  STEP_H,
  STEP_COUNT,
  W_NAGR,
  PWC170,
  INDP,
  RUN_30,
  RUN_6,
  RUN_3_10,
  JUMP,
  PULL_UP_SHORT,
  PULL_UP_LONG,
  BODY_TILT,
  HR,
  MEAN,
  XMAX,
  XMIN,
  MX_DMN,
  MX_RMN,
  RM_SSD,
  PNN50,
  SDNN,
  CV,
  D,
  MO,
  AMOSDNN,
  AMO50,
  AMO7_8,
  CC1,
  CC0,
  NARR,
  SI,
  TP,
  HF,
  LF,
  VLF,
  ULF,
  HFMX,
  LFMX,
  VLFMX,
  ULFMX,
  THF,
  TLF,
  TVLF,
  TULF,
  PHF,
  PLF,
  PVLF,
  LF_HF,
  VLF_HF,
  IC,
  PARS,
  NTI,
  CONTROL_KIND,
  R50,
  XC50,
  R5,
  XC5,
  ANGLE_PHASE_50,
  IMT,
  ZHM,
  ZHM_SHARE,
  TM,
  AKM,
  AKM_SHARE,
  SMM,
  SMM_SHARE,
  BE,
  SE,
  WATER,
  WATER_EXTRA,
  WATER_INSIDE,
  END0,
  MESO,
  ECTO,
  MESO_PHI_50,
  IZHM,
  ITM,
  IAKM,
  ISMM,
  DIZHM,
  DITM,
  DIAKM,
  DISMM,
  MINERAL_WEIGHT,
  SOFT_FABRICS_MINERAL_WEIGHT,
  BONE_MINERAL_WEIGHT,
  MINERAL_WEIGHT_TM,
  SOFT_FABRICS_MINERAL_WEIGHT_TM,
  BONE_MINERAL_WEIGHT_TM,
}

export enum FieldExcelType {
  GENERAL_INFO = "generalInfo",
  HEALTH_INFO = "healthInfo",
  PHYSICAL_INFO = "physicalInfo",
  FUNC_AND_PHYS_PERF_INFO = "funcAndPhysPerfInfo",
  TESTS_INFO = "testsInfo",
  HEAT_INFO = "heatInfo",
  BIOM_INFO = "biomInfo",
}

interface CustomColDef extends ColDef {
  field: string;
  headerName: string;
}

export const excelFields: Record<ExcelFieldName, CustomColDef> = {
  [ExcelFieldName.FIO]: {
    field: "B",
    headerName: "ФИО",
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.EDUCATION_ORG]: {
    field: "C",
    headerName: "Образовательная организация",
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.CITY]: {
    field: "D",
    headerName: "Населенный пункт",
    filter: AgGridFilter.SELECT,
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.SEX]: {
    field: "E",
    headerName: "Пол",
    filter: AgGridFilter.SELECT,
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.CLASS_NAME]: {
    field: "className",
    headerName: "Номер класса",
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.CLASS]: {
    field: "F",
    headerName: "Класс",
    cellClass: FieldExcelType.GENERAL_INFO,
    headerClass: FieldExcelType.GENERAL_INFO,
  },
  [ExcelFieldName.EXAMINATION_DATE]: {
    field: "G",
    headerName: "Дата обследования",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.BIRTHDAY]: {
    field: "H",
    headerName: "Дата рождения",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.AGE]: {
    field: "I",
    headerName: "Возраст",
    filter: AgGridFilter.NUMBER,
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.EXPERIENCE]: {
    field: "J",
    headerName: "Стаж (лет)",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.SPORT_KIND]: {
    field: "K",
    headerName: "Вид спорта",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.HEALTH_GROUP]: {
    field: "L",
    headerName: "Группа здоровья",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.PHYSICAL_GROUP]: {
    field: "M",
    headerName: "Физкультурная группа",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.DISEASES_YEAR_NUMBER]: {
    field: "N",
    headerName: "Кратность заболеваний в учебном году(раз)",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.DISEASES_YEAR_DURATION]: {
    field: "O",
    headerName: "Длительность заболеваний в учебном году(всего дней)",
    cellClass: FieldExcelType.HEALTH_INFO,
    headerClass: FieldExcelType.HEALTH_INFO,
  },
  [ExcelFieldName.GROWTH]: {
    field: "P",
    headerName: "Рост(см)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.WEIGHT]: {
    field: "Q",
    headerName: "Вес(кг)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.OKG_REST]: {
    field: "R",
    headerName: "ОГК в покое(см)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.OKG_SIGH]: {
    field: "S",
    headerName: "ОГК на вдохе(см)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.OKG_EXHALATION]: {
    field: "T",
    headerName: "ОГК на выдохе(см)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.ZHEL]: {
    field: "U",
    headerName: "ЖЕЛ(см3)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.KD_RIGHT]: {
    field: "V",
    headerName: "КД(пр.)(кг)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.KD_LEFT]: {
    field: "W",
    headerName: "КД(лев.)(кг)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.KZHS_UNDER_UNDER_SHOULDER]: {
    field: "X",
    headerName: "КЖС под лопаткой(мм)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.KZHS_ON_BELLY]: {
    field: "Y",
    headerName: "КЖС на животе(мм)",
    cellClass: FieldExcelType.PHYSICAL_INFO,
    headerClass: FieldExcelType.PHYSICAL_INFO,
  },
  [ExcelFieldName.KZHS_ON_BICEPS]: {
    field: "Z",
    headerName: "КЖС над бицепсом(мм)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.AD_SYSTOLIC]: {
    field: "AA",
    headerName: "АД сист.(мм рс.ст.)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.AD_DIASTOLIC]: {
    field: "AB",
    headerName: "АД диаст.(мм рс.ст.)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS_LOAD]: {
    field: "AC",
    headerName: "ЧСС покой",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS_REST]: {
    field: "AD",
    headerName: "ЧСС после нагрузки",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS1]: {
    field: "AE",
    headerName: "ЧСС1",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS2]: {
    field: "AF",
    headerName: "ЧСС2",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS3]: {
    field: "AG",
    headerName: "ЧСС3",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS4]: {
    field: "AH",
    headerName: "ЧСС4",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.CHSS5]: {
    field: "AI",
    headerName: "ЧСС5",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.STEP_H]: {
    field: "AJ",
    headerName: "h ступени(см)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.STEP_COUNT]: {
    field: "AK",
    headerName: "Число восхождений за мин",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.W_NAGR]: {
    field: "AL",
    headerName: "W нагр(кгм/мин)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.PWC170]: {
    field: "AM",
    headerName: "PWC170(кгм/мин)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.INDP]: {
    field: "AN",
    headerName: "ИНПД(ус.ед.)",
    cellClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
    headerClass: FieldExcelType.FUNC_AND_PHYS_PERF_INFO,
  },
  [ExcelFieldName.RUN_30]: {
    field: "AO",
    headerName: "Бег 30м(с)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.RUN_6]: {
    field: "AP",
    headerName: "Бег 6 мин(м)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.RUN_3_10]: {
    field: "AQ",
    headerName: "Бег челночный 3х10(с)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.JUMP]: {
    field: "AR",
    headerName: "Прыжок в длину с места(см)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.PULL_UP_SHORT]: {
    field: "AS",
    headerName: "Потягивание на низкой перекладине(раз)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.PULL_UP_LONG]: {
    field: "AT",
    headerName: "Потягивание на высокой перекладине(раз)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.BODY_TILT]: {
    field: "AU",
    headerName: "Наклон туловища вперед из положения стоя(см)",
    cellClass: FieldExcelType.TESTS_INFO,
    headerClass: FieldExcelType.TESTS_INFO,
  },
  [ExcelFieldName.HR]: {
    field: "AV",
    headerName: "HR(уд./мин)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.MEAN]: {
    field: "AW",
    headerName: "Mean(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.XMAX]: {
    field: "AX",
    headerName: "XMax(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.XMIN]: {
    field: "AY",
    headerName: "XMin(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.MX_DMN]: {
    field: "AZ",
    headerName: "MxDMn(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.MX_RMN]: {
    field: "BA",
    headerName: "MxRMn(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.RM_SSD]: {
    field: "BB",
    headerName: "RMSSD(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.PNN50]: {
    field: "BC",
    headerName: "pNN50(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.SDNN]: {
    field: "BD",
    headerName: "SDNN(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.CV]: {
    field: "BR",
    headerName: "CV(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.D]: {
    field: "BF",
    headerName: "D(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.MO]: {
    field: "BG",
    headerName: "Mo(мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.AMOSDNN]: {
    field: "BH",
    headerName: "AMoSDNN(%/SDNN)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.AMO50]: {
    field: "BI",
    headerName: "AMo50(%/50 мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.AMO7_8]: {
    field: "BJ",
    headerName: "AMo7.8(%/7.8 мс)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.CC1]: {
    field: "BK",
    headerName: "CC1",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.CC0]: {
    field: "BL",
    headerName: "CC0",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.NARR]: {
    field: "BM",
    headerName: "NArr(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.SI]: {
    field: "BN",
    headerName: "SI",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.TP]: {
    field: "BO",
    headerName: "TP(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.HF]: {
    field: "BP",
    headerName: "HF(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.LF]: {
    field: "BQ",
    headerName: "LF(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.VLF]: {
    field: "BR",
    headerName: "VLF(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.ULF]: {
    field: "BS",
    headerName: "ULF(мс2)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.HFMX]: {
    field: "BT",
    headerName: "HFmx(мс2/Гц)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.LFMX]: {
    field: "BU",
    headerName: "LFmx(мс2/Гц)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.VLFMX]: {
    field: "BV",
    headerName: "VKFmx(мс2/Гц)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.ULFMX]: {
    field: "BW",
    headerName: "ULF(мс2/Гц)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.THF]: {
    field: "BX",
    headerName: "THF(с)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.TLF]: {
    field: "BY",
    headerName: "TLF(с)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.TVLF]: {
    field: "BZ",
    headerName: "TVLF(с)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.TULF]: {
    field: "CA",
    headerName: "TULF(с)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.PHF]: {
    field: "CB",
    headerName: "PHF(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.PLF]: {
    field: "CC",
    headerName: "PLF(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.PVLF]: {
    field: "CD",
    headerName: "PVLF(%)",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.LF_HF]: {
    field: "CE",
    headerName: "LF/HF",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.VLF_HF]: {
    field: "CF",
    headerName: "VLF/HF",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.IC]: {
    field: "CG",
    headerName: "IC",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.PARS]: {
    field: "CH",
    headerName: "ПАРС",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.NTI]: {
    field: "CI",
    headerName: "НТИ",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.CONTROL_KIND]: {
    field: "CJ",
    headerName: "Тип регул.",
    cellClass: FieldExcelType.HEAT_INFO,
    headerClass: FieldExcelType.HEAT_INFO,
  },
  [ExcelFieldName.R50]: {
    field: "CK",
    headerName: "R50(ом)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.XC50]: {
    field: "CL",
    headerName: "Xc50(ом)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.R5]: {
    field: "CM",
    headerName: "R5(ом)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.XC5]: {
    field: "CN",
    headerName: "Xc5(ом)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ANGLE_PHASE_50]: {
    field: "CO",
    headerName: "Фаз. угол 50Кгц(град.)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.IMT]: {
    field: "CP",
    headerName: "ИМТ(кг/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ZHM]: {
    field: "CQ",
    headerName: "ЖМ(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ZHM_SHARE]: {
    field: "CR",
    headerName: "Доля ЖМ(%)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.TM]: {
    field: "CS",
    headerName: "ТМ(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.AKM]: {
    field: "CT",
    headerName: "АКМ(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.AKM_SHARE]: {
    field: "CU",
    headerName: "Доля АКМ(%)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.SMM]: {
    field: "CV",
    headerName: "СММ(%)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.SMM_SHARE]: {
    field: "CW",
    headerName: "Доля СММ(%)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.BE]: {
    field: "CX",
    headerName: "Осн.Обм.(ккал)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.SE]: {
    field: "CY",
    headerName: "Уд.Обм..(ккал/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.WATER]: {
    field: "CZ",
    headerName: "Вода(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.WATER_EXTRA]: {
    field: "DA",
    headerName: "Внекл.Вода(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.WATER_INSIDE]: {
    field: "DB",
    headerName: "Внутрикл.Вода(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.END0]: {
    field: "DC",
    headerName: "END0",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.MESO]: {
    field: "DD",
    headerName: "MESO",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ECTO]: {
    field: "DE",
    headerName: "ECTO",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.MESO_PHI_50]: {
    field: "DF",
    headerName: "MESO*Phi50",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.IZHM]: {
    field: "DG",
    headerName: "ИЖМ(кг/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ITM]: {
    field: "DH",
    headerName: "ИТМ(кг/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.IAKM]: {
    field: "DI",
    headerName: "ИАКМ(кг/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.ISMM]: {
    field: "DJ",
    headerName: "ИСММ(кг/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.DIZHM]: {
    field: "DK",
    headerName: "ДИЖМ(1/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.DITM]: {
    field: "DL",
    headerName: "ДИТМ(1/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.DIAKM]: {
    field: "DM",
    headerName: "ДИАКМ(1/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.DISMM]: {
    field: "DN",
    headerName: "ДИСММ(1/кв.м)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.MINERAL_WEIGHT]: {
    field: "DO",
    headerName: "Минер.масса(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.SOFT_FABRICS_MINERAL_WEIGHT]: {
    field: "DP",
    headerName: "Мин. масса мяг. тканей(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.BONE_MINERAL_WEIGHT]: {
    field: "DQ",
    headerName: "Мин. масса костей(кг)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.MINERAL_WEIGHT_TM]: {
    field: "DR",
    headerName: "Минер. масса(%ТМ)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.SOFT_FABRICS_MINERAL_WEIGHT_TM]: {
    field: "DS",
    headerName: "Мин масса мяг. тканей(%ТМ)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
  [ExcelFieldName.BONE_MINERAL_WEIGHT_TM]: {
    field: "DT",
    headerName: "Мин. масса костей(%ТМ)",
    cellClass: FieldExcelType.BIOM_INFO,
    headerClass: FieldExcelType.BIOM_INFO,
  },
};
